import './globals.css';

import type { Metadata } from 'next';
import { FC, PropsWithChildren } from 'react';
import { Toaster } from 'sonner';

import { inter } from '@/configs/fonts';
import { ThemeProvider } from '@/providers/theme/ThemeProvider';

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app'
};

const RootLayout: FC<PropsWithChildren> = ({ children }) => {
    return (
        <html lang="en">
            <body className={inter.className}>
                <ThemeProvider attribute="class" defaultTheme="system" enableSystem disableTransitionOnChange>
                    <main>{children}</main>
                    <Toaster />
                </ThemeProvider>
            </body>
        </html>
    );
};

export default RootLayout;
